---
abstract: 'OAI-PMH provider backed by a searchable Catmandu::Store'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
  - 'Nicolas Franck <nicolas.franck@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Catmandu-OAI
provides:
  Dancer::Plugin::Catmandu::OAI:
    file: lib/Dancer/Plugin/Catmandu/OAI.pm
    version: 0.0304
requires:
  Catmandu: 0.8013
  Catmandu::Exporter::Template: 0.002000
  Clone: 0
  Dancer: 1.3121
  DateTime: 0
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.0304
